FROM python:3.10

WORKDIR /star_burger_docker/back

COPY . .
RUN mkdir -p /star_burger_docker/staticfiles/assets
RUN mkdir -p /star_burger_docker/staticfiles/bundles
RUN pip install -r requirements.txt
RUN python3 manage.py collectstatic --noinput

