# Generated by Django 3.2.15 on 2023-11-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_rename_amount_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'Обработанный'), ('FS', 'Необработанный')], db_index=True, default='0', max_length=2),
        ),
    ]
