# Generated by Django 3.2.15 on 2023-11-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FS', 'Обработанный'), ('PR', 'Необработанный')], db_index=True, default='Необработанный', max_length=2),
        ),
    ]
