# Generated by Django 3.2.15 on 2023-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20231122_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Электронно')], db_index=True, default='Электронно', max_length=30, verbose_name='способ оплаты'),
        ),
    ]
