# Generated by Django 3.2.15 on 2023-11-26 17:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantmenuitem',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
    ]
