# Generated by Django 3.2.15 on 2023-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_restaurantmenuitem_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
    ]
