# Generated by Django 3.2.15 on 2024-01-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20240127_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FS', 'Обработанный'), ('PR', 'Необработанный')], db_index=True, default='Необработанный', max_length=40, verbose_name='статус'),
        ),
    ]
