# Generated by Django 3.2.15 on 2024-02-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20240128_1903'),
        ('foodcartapp', '0057_alter_order_status'),
    ]

    operations = [
    ]
