# Generated by Django 3.2.15 on 2023-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_place', models.CharField(db_index=True, max_length=50, verbose_name='Адрес')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Долгота')),
                ('request_date', models.DateField(verbose_name='Дата запроса')),
            ],
            options={
                'unique_together': {('address_place', 'lat', 'lon')},
            },
        ),
    ]
