# Generated by Django 3.2.15 on 2023-11-26 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса'),
        ),
    ]
