FROM node:16.16.0

WORKDIR /star_burger_docker/front

COPY . .

RUN npm ci --dev
RUN ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir /starburger_docker/staticfiles/bundles --public-url="./"